# ============================================================
# Stage 1: Build
# ============================================================
FROM docker.io/library/node:20-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

RUN git clone https://github.com/AL3X09/vue-admin.git .

# Declarar todos los ARGs que vienen del .env
ARG VITE_API_BASE_URL
ARG VITE_API_TIMEOUT
ARG VITE_APP_NAME
ARG VITE_APP_VERSION
ARG VITE_APP_DEBUG
ARG VITE_BASE_URL
ARG VITE_TOKEN_EXPIRATION_MINUTES
ARG VITE_REMEMBER_ME_DAYS
ARG VITE_TOKEN_STORAGE_KEY
ARG VITE_USER_STORAGE_KEY
ARG VITE_PASSWORD_CHANGE_STORAGE_KEY
ARG VITE_TOAST_DURATION
ARG VITE_TOAST_POSITION
ARG VITE_DEFAULT_ITEMS_PER_PAGE
ARG VITE_ITEMS_PER_PAGE_OPTIONS
ARG VITE_MAX_FILE_SIZE_MB
ARG VITE_ALLOWED_IMAGE_TYPES
ARG VITE_ALLOWED_DOCUMENT_TYPES
ARG VITE_PROTECTED_REDIRECT_URLS
ARG VITE_MIN_PASSWORD_LENGTH
ARG VITE_PASSWORD_PATTERN
ARG VITE_MAX_LOGIN_ATTEMPTS
ARG VITE_LOGIN_LOCKOUT_MINUTES
ARG VITE_ENABLE_REGISTRATION
ARG VITE_ENABLE_PASSWORD_CHANGE
ARG VITE_ENABLE_DARK_MODE
ARG VITE_ENABLE_NOTIFICATIONS
ARG VITE_ENABLE_DEBUG_LOGS
ARG VITE_ENABLE_DATA_EXPORT
ARG VITE_CORS_ALLOWED_ORIGINS

# Exponer todos como ENV para que Vite los lea en build time
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_API_TIMEOUT=$VITE_API_TIMEOUT \
    VITE_APP_NAME=$VITE_APP_NAME \
    VITE_APP_VERSION=$VITE_APP_VERSION \
    VITE_APP_DEBUG=$VITE_APP_DEBUG \
    VITE_BASE_URL=$VITE_BASE_URL \
    VITE_TOKEN_EXPIRATION_MINUTES=$VITE_TOKEN_EXPIRATION_MINUTES \
    VITE_REMEMBER_ME_DAYS=$VITE_REMEMBER_ME_DAYS \
    VITE_TOKEN_STORAGE_KEY=$VITE_TOKEN_STORAGE_KEY \
    VITE_USER_STORAGE_KEY=$VITE_USER_STORAGE_KEY \
    VITE_PASSWORD_CHANGE_STORAGE_KEY=$VITE_PASSWORD_CHANGE_STORAGE_KEY \
    VITE_TOAST_DURATION=$VITE_TOAST_DURATION \
    VITE_TOAST_POSITION=$VITE_TOAST_POSITION \
    VITE_DEFAULT_ITEMS_PER_PAGE=$VITE_DEFAULT_ITEMS_PER_PAGE \
    VITE_ITEMS_PER_PAGE_OPTIONS=$VITE_ITEMS_PER_PAGE_OPTIONS \
    VITE_MAX_FILE_SIZE_MB=$VITE_MAX_FILE_SIZE_MB \
    VITE_ALLOWED_IMAGE_TYPES=$VITE_ALLOWED_IMAGE_TYPES \
    VITE_ALLOWED_DOCUMENT_TYPES=$VITE_ALLOWED_DOCUMENT_TYPES \
    VITE_PROTECTED_REDIRECT_URLS=$VITE_PROTECTED_REDIRECT_URLS \
    VITE_MIN_PASSWORD_LENGTH=$VITE_MIN_PASSWORD_LENGTH \
    VITE_PASSWORD_PATTERN=$VITE_PASSWORD_PATTERN \
    VITE_MAX_LOGIN_ATTEMPTS=$VITE_MAX_LOGIN_ATTEMPTS \
    VITE_LOGIN_LOCKOUT_MINUTES=$VITE_LOGIN_LOCKOUT_MINUTES \
    VITE_ENABLE_REGISTRATION=$VITE_ENABLE_REGISTRATION \
    VITE_ENABLE_PASSWORD_CHANGE=$VITE_ENABLE_PASSWORD_CHANGE \
    VITE_ENABLE_DARK_MODE=$VITE_ENABLE_DARK_MODE \
    VITE_ENABLE_NOTIFICATIONS=$VITE_ENABLE_NOTIFICATIONS \
    VITE_ENABLE_DEBUG_LOGS=$VITE_ENABLE_DEBUG_LOGS \
    VITE_ENABLE_DATA_EXPORT=$VITE_ENABLE_DATA_EXPORT \
    VITE_CORS_ALLOWED_ORIGINS=$VITE_CORS_ALLOWED_ORIGINS

RUN npm ci
RUN node node_modules/vite/bin/vite.js build

# ============================================================
# Stage 2: Producción con Nginx
# ============================================================
FROM docker.io/library/nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://localhost/ || exit 1

CMD ["nginx", "-g", "daemon off;"]